### ISSUE TITLE
Token & Permission

### ISSUE THREAD

**Issue by istarengwa** [aglerr/ItemSkins-Files#2]
For the moment when we activate this option:

 " remove-skin-no-permission: true "
 
 when you use a token when you don't have the perm of the item, you can't have the skin, it would be nice to have an option to be able to use the tokens without having the permissions of the objects

**Comment by mdaffa48** [comment]
Let me recap the feature suggestion, we have talked on Discord and you want the player to use the skin that is applied by physical skin even though the player doesn't have permission to use the skin? So make it exceptional If the skin is applied by physical skin.

I will post an update regarding the development of this feature here. Please be patient.

**Comment by mdaffa48** [comment]
Implemented on v1.8 and it's currently available on any marketplace.
