### ISSUE TITLE
SUGGESTION - Adding Color option to a Item Skin

### ISSUE THREAD

**Issue by maxofrank** [aglerr/ItemSkins-Files#6]
It would be great if the plugin support a default color for the cosmetic item. Becouse in some servers we use Leather Horse Armors like dyable swords, and plugins like ItemsAdder make leather armor have different textures depending of the armor color. Adding an option like the Player Cosmetics plugin would be fantastic. Something like this I mean:

material: leather_chestplate

custom-model-data: 2022

permission: "itemskins.armor.steel.armor"

default-color:
  red: 12
  green: 4
  blue: 220

Thanks for reading!!

**Comment by mdaffa48** [comment]
Great suggestion, this feature is already implemented on the code and will be available publicly on the new version!
